### ISSUE TITLE
System information hangs explorer

### ISSUE THREAD

**Issue by soverc** [Ulterius/client#4]
If I click System Information, I never get any info and explorer is in a hung state that I can not click any open folders or anything on taskbar.  I have to kill the explorer process to return to normal.

Basic machine specs -Windows 10, i7 32gig

Otherwise good job

**Comment by garfyville** [comment]
Initially had a similar problem, turned out I hadn't unlocked a keybase.io secure drive and Ulterius was failing to get past an access denied error. Discovered this in the log.
scanning K:
DeviceIoControl() returned false
Incorrect function
File Database Ready
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.DriveInfo.get_TotalFreeSpace()

**Comment by Codeusa** [comment]
@garfyville thanks for that, I didn't expect that to actually be an issue. I'll patch it in a bit
